version: '3.8'

services:
  mysql:
    image: mysql:8.0
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root  # Set the root password
      MYSQL_DATABASE: issue_tracker
    volumes:
      - db-data:/var/lib/mysql

volumes:
  db-data: