server:
  port: 8083

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/issue_tracker
    username: root
    password: root

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false

  security:
    user:
      name: admin
      password: admin

flyway:
  url: jdbc:mysql://localhost:3306/issue_tracker
  user: root
  password: root
  locations: classpath:db/migration
